FROM node:22.16.0-alpine3.20 AS development
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm i
COPY . .
RUN npm run build

# BUILD
FROM node:22.16.0-alpine3.20
WORKDIR /usr/src/app

ENV NODE_ENV=development
ENV PORT=4002

COPY package*.json ./
RUN npm ci

# Copy source code
COPY . .
COPY --from=development /usr/src/app/node_modules ./node_modules
COPY --from=development /usr/src/app/dist ./dist
EXPOSE 4002

CMD [ "npm", "run", "start:prod" ]